version: 0.0
os: linux

files:
  - source: docker-compose.prod.yml
    destination: /home/ubuntu/tara_dev_backend
  - source: nginx/tara_prod.conf
    destination: /tmp

hooks:
  BeforeInstall:
    - location: scripts/beforeinstall.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/afterinstall.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/applicationstart.sh
      timeout: 600
      runas: ubuntu
  ApplicationStop:
    - location: scripts/applicationstop.sh
      timeout: 180
      runas: ubuntu