# Generated by Django 5.0.4 on 2025-09-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docwallet', '0003_document_document_name_trgm_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='hsn_codes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=40)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'hsn',
                'indexes': [models.Index(fields=['code'], name='hsn_code_32bfac_idx')],
            },
        ),
    ]
