# Generated by Django 5.0.4 on 2025-09-02 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0021_alter_employeeeducationdetails_upload_certificate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemanagement',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeemanagement',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_department', to='payroll.departments'),
        ),
        migrations.AlterField(
            model_name='employeemanagement',
            name='designation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_designation', to='payroll.designation'),
        ),
        migrations.AlterField(
            model_name='employeemanagement',
            name='doj',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeemanagement',
            name='work_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_work_location', to='payroll.worklocations'),
        ),
        migrations.AddConstraint(
            model_name='employeemanagement',
            constraint=models.UniqueConstraint(fields=('user', 'payroll'), name='unique_user_per_payroll'),
        ),
    ]
