# Generated by Django 5.0.4 on 2025-09-03 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0022_employeemanagement_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancelog',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='payroll.employeemanagement'),
        ),
        migrations.AlterField(
            model_name='employeeeducationdetails',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_details', to='payroll.employeemanagement'),
        ),
        migrations.AlterField(
            model_name='employeefacerecognition',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='payroll.employeemanagement'),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='cc_to',
            field=models.ManyToManyField(blank=True, related_name='cc_leaves', to='payroll.employeemanagement'),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_applications', to='payroll.employeemanagement'),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_leaves', to='payroll.employeemanagement'),
        ),
        migrations.AlterField(
            model_name='leavenotification',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.employeemanagement'),
        ),
    ]
